#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2154

DEVVM_CONFIG="${DEVVM_CONFIG:-$HOME/.config/devvm}"
DEVVM_STATE="${DEVVM_STATE:-$HOME/.local/share/devvm-state}"
DEVVM_GENERATED="${DEVVM_GENERATED:-$DEVVM_STATE/generated}"

devvm_load_config() {
	local default_config user_config local_config
	default_config="$DEVVM_CORE/defaults/config.env"
	user_config="$DEVVM_CONFIG/config.env"
	local_config="$DEVVM_CONFIG/local.env"

	devvm_check_required_file "$default_config"
	devvm_load_env_file "$default_config"

	if [ -f "$user_config" ]; then
		devvm_load_env_file "$user_config"
	fi

	if [ -f "$local_config" ]; then
		devvm_load_env_file "$local_config"
	fi

	VM_PREFIX="${VM_PREFIX:-devvm}"
	DEFAULT_DISTRO="${DEFAULT_DISTRO:-fedora}"
	DEFAULT_CPUS="${DEFAULT_CPUS:-4}"
	DEFAULT_MEMORY="${DEFAULT_MEMORY:-8GiB}"
	DEFAULT_DISK="${DEFAULT_DISK:-80GiB}"
	DEFAULT_PORTS="${DEFAULT_PORTS:-}"
	DEFAULT_MOUNTS="${DEFAULT_MOUNTS:-}"
	GLOBAL_PACKAGES="${GLOBAL_PACKAGES:-}"
	GLOBAL_SETUP_SCRIPTS="${GLOBAL_SETUP_SCRIPTS:-}"
	GLOBAL_MOUNTS="${GLOBAL_MOUNTS:-}"
	DEVVM_ALLOW_SENSITIVE_MOUNTS="${DEVVM_ALLOW_SENSITIVE_MOUNTS:-0}"
	LIMA_TEMPLATE="${LIMA_TEMPLATE:-template:fedora}"
	LIMA_ARCH="${LIMA_ARCH:-aarch64}"
	DEVVM_GUEST_USER="${DEVVM_GUEST_USER:-$(devvm_host_user)}"
	DEVVM_GUEST_HOME="${DEVVM_GUEST_HOME:-/home/$DEVVM_GUEST_USER}"
	DEVVM_CODE_DIR="${DEVVM_CODE_DIR:-$DEVVM_GUEST_HOME/code}"
	DEVVM_BACKUP_DIR="${DEVVM_BACKUP_DIR:-$DEVVM_STATE/backups}"
	DEVVM_BACKUP_INCLUDE_SECRETS="${DEVVM_BACKUP_INCLUDE_SECRETS:-1}"
	DEVVM_RESTORE_INCLUDE_SECRETS="${DEVVM_RESTORE_INCLUDE_SECRETS:-1}"
	DEVVM_BACKUP_ENCRYPT="${DEVVM_BACKUP_ENCRYPT:-1}"
	DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS="${DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS:-0}"
	DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS="$(devvm_bool "$DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS" "DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS")"
	DEVVM_BACKUP_EXCLUDES="${DEVVM_BACKUP_EXCLUDES:-*/node_modules */.cache */target */.venv}"
	DEVVM_RELEASE_SIGNER_FINGERPRINTS="${DEVVM_RELEASE_SIGNER_FINGERPRINTS:-}"
	DEVVM_UPDATE_CHECK_ENABLED="${DEVVM_UPDATE_CHECK_ENABLED:-1}"
	DEVVM_UPDATE_CHECK_ENABLED="$(devvm_bool "$DEVVM_UPDATE_CHECK_ENABLED" "DEVVM_UPDATE_CHECK_ENABLED")"
	DEVVM_UPDATE_CHECK_INTERVAL_SECONDS="${DEVVM_UPDATE_CHECK_INTERVAL_SECONDS:-86400}"
	case "$DEVVM_UPDATE_CHECK_INTERVAL_SECONDS" in
	'' | *[!0-9]*) devvm_die "DEVVM_UPDATE_CHECK_INTERVAL_SECONDS must be a non-negative integer" ;;
	esac
	GIT_USER_NAME="${GIT_USER_NAME:-}"
	GIT_USER_EMAIL="${GIT_USER_EMAIL:-}"
	AI_VM_NAME="${AI_VM_NAME:-ai}"
	AI_VM_CPUS="${AI_VM_CPUS:-6}"
	AI_VM_MEMORY="${AI_VM_MEMORY:-12GiB}"
	AI_VM_DISK="${AI_VM_DISK:-120GiB}"
	AI_VM_CODE_DIR="${AI_VM_CODE_DIR:-$DEVVM_GUEST_HOME/ai}"
	AI_LLAMA_PACKAGES="${AI_LLAMA_PACKAGES:-llama-cpp}"
	AI_LLAMA_MOUNTS="${AI_LLAMA_MOUNTS:-}"
	AI_LLAMA_MODELS_DIR="${AI_LLAMA_MODELS_DIR:-$DEVVM_GUEST_HOME/models}"
	AI_LLAMA_MODELS="${AI_LLAMA_MODELS:-}"
	AI_LLAMA_MODEL="${AI_LLAMA_MODEL:-}"
	AI_ALLOW_HTTP_MODEL_URLS="${AI_ALLOW_HTTP_MODEL_URLS:-0}"
	AI_ALLOW_HTTP_MODEL_URLS="$(devvm_bool "$AI_ALLOW_HTTP_MODEL_URLS" "AI_ALLOW_HTTP_MODEL_URLS")"
	AI_LLAMA_LISTEN_HOST="${AI_LLAMA_LISTEN_HOST:-0.0.0.0}"
	AI_LLAMA_SERVER_PORT="${AI_LLAMA_SERVER_PORT:-8080}"
	AI_LLAMA_HOST_PORT="${AI_LLAMA_HOST_PORT:-18080}"
	AI_LLAMA_CTX_SIZE="${AI_LLAMA_CTX_SIZE:-4096}"
	AI_LLAMA_EXTRA_ARGS="${AI_LLAMA_EXTRA_ARGS:-}"
	AI_LLAMA_BASE_URL="${AI_LLAMA_BASE_URL:-http://host.lima.internal:$AI_LLAMA_HOST_PORT/v1}"
	export VM_PREFIX DEFAULT_DISTRO DEFAULT_CPUS DEFAULT_MEMORY DEFAULT_DISK
	export DEFAULT_PORTS DEFAULT_MOUNTS GLOBAL_PACKAGES GLOBAL_SETUP_SCRIPTS
	export GLOBAL_MOUNTS DEVVM_ALLOW_SENSITIVE_MOUNTS
	export LIMA_TEMPLATE LIMA_ARCH DEVVM_CODE_DIR
	export GIT_USER_NAME GIT_USER_EMAIL DEVVM_GUEST_USER
	export DEVVM_GUEST_HOME
	export DEVVM_BACKUP_DIR DEVVM_BACKUP_INCLUDE_SECRETS DEVVM_RESTORE_INCLUDE_SECRETS
	export DEVVM_BACKUP_ENCRYPT DEVVM_BACKUP_ALLOW_PLAINTEXT_SECRETS DEVVM_BACKUP_EXCLUDES
	export DEVVM_RELEASE_SIGNER_FINGERPRINTS DEVVM_UPDATE_CHECK_ENABLED
	export DEVVM_UPDATE_CHECK_INTERVAL_SECONDS
	export AI_VM_NAME AI_VM_CPUS AI_VM_MEMORY AI_VM_DISK AI_VM_CODE_DIR
	export AI_LLAMA_PACKAGES AI_LLAMA_MOUNTS AI_LLAMA_MODELS_DIR AI_LLAMA_MODELS
	export AI_LLAMA_MODEL AI_ALLOW_HTTP_MODEL_URLS AI_LLAMA_LISTEN_HOST
	export AI_LLAMA_SERVER_PORT AI_LLAMA_HOST_PORT AI_LLAMA_CTX_SIZE
	export AI_LLAMA_EXTRA_ARGS AI_LLAMA_BASE_URL
}

devvm_init() {
	devvm_load_config
	devvm_ensure_dir "$DEVVM_CONFIG/vms"
	devvm_ensure_dir "$DEVVM_STATE"
	devvm_ensure_dir "$DEVVM_GENERATED"

	if [ ! -f "$DEVVM_CONFIG/config.env" ]; then
		cp "$DEVVM_CORE/defaults/config.env" "$DEVVM_CONFIG/config.env"
		devvm_log "created $DEVVM_CONFIG/config.env"
	fi

	if [ ! -f "$DEVVM_CONFIG/local.env" ]; then
		touch "$DEVVM_CONFIG/local.env"
		chmod 0600 "$DEVVM_CONFIG/local.env"
		devvm_log "created $DEVVM_CONFIG/local.env"
	fi

	devvm_log "initialized DevVM config at $DEVVM_CONFIG"
}
